# Generated by Django 4.0.4 on 2022-06-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shelter', '0004_breed_color_alter_pet_kind_of_pet_alter_pet_pet_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(blank=True, upload_to='pet_shelter/media/photos'),
        ),
    ]
