# Generated by Django 4.0.4 on 2022-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shelter', '0002_owner_pet_delete_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(max_length=120),
        ),
    ]
