# Generated by Django 4.0.4 on 2022-06-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shelter', '0003_alter_owner_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='kind_of_pet',
            field=models.CharField(choices=[('CT', 'cat'), ('DG', 'dog'), ('PT', 'parrot')], default='CT', max_length=2, verbose_name='Вид животного'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(max_length=100, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='pet_shelter.breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='pet_shelter.color'),
        ),
    ]
