# Generated by Django 4.0.4 on 2022-06-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shelter', '0005_pet_description_pet_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(blank=True, upload_to='media/photos'),
        ),
    ]
